from __future__ import annotations

import logging
import time
import uuid
from pathlib import Path

logger = logging.getLogger(__name__)

_DEFAULT_TTL_HOURS = 24

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — Nexus</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    max-width: 800px; margin: 40px auto; padding: 0 20px;
    color: #1e293b; background: #f8fafc; line-height: 1.6;
  }}
  h1 {{ color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }}
  pre {{ background: #1e293b; color: #e2e8f0; padding: 16px; border-radius: 8px;
         overflow-x: auto; font-size: 14px; }}
  code {{ background: #e2e8f0; padding: 2px 6px; border-radius: 4px; font-size: 14px; }}
  pre code {{ background: none; padding: 0; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
  th, td {{ border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }}
  th {{ background: #f1f5f9; font-weight: 600; }}
  a {{ color: #2563eb; }}
  .meta {{ color: #64748b; font-size: 14px; margin-bottom: 24px; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background: #0f172a; color: #e2e8f0; }}
    h1 {{ color: #f1f5f9; border-color: #334155; }}
    pre {{ background: #1e293b; }}
    code {{ background: #334155; }}
    th {{ background: #1e293b; }}
    th, td {{ border-color: #334155; }}
    .meta {{ color: #94a3b8; }}
  }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="meta">Generated by Nexus &middot; {timestamp}</p>
{content}
</body>
</html>"""


class ContentStore:
    def __init__(self, views_dir: str = "data/views", ttl_hours: int = _DEFAULT_TTL_HOURS) -> None:
        self._views_dir = Path(views_dir)
        self._views_dir.mkdir(parents=True, exist_ok=True)
        self._ttl_seconds = ttl_hours * 3600

    def store(self, content: str, title: str = "Nexus Response") -> str:
        view_id = uuid.uuid4().hex[:8]
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S %Z")
        html = _HTML_TEMPLATE.format(title=title, content=content, timestamp=timestamp)
        path = self._views_dir / f"{view_id}.html"
        path.write_text(html)
        return view_id

    def get(self, view_id: str) -> str | None:
        if not view_id.isalnum() or ".." in view_id:
            return None
        path = self._views_dir / f"{view_id}.html"
        if not path.exists():
            return None
        age = time.time() - path.stat().st_mtime
        if age > self._ttl_seconds:
            path.unlink(missing_ok=True)
            return None
        return path.read_text()

    def cleanup(self) -> int:
        removed = 0
        if not self._views_dir.exists():
            return removed
        for path in self._views_dir.glob("*.html"):
            age = time.time() - path.stat().st_mtime
            if age > self._ttl_seconds:
                path.unlink(missing_ok=True)
                removed += 1
        return removed
